### ISSUE TITLE
Can autolin be used in non-parsimony trees?

### ISSUE THREAD

**Issue by santanaw** [jmcbroome/automate-lineages-prototype#7]
Hi @jmcbroome,

Many thanks for developing autolin! I did noticed that autolin can be used with parsimony phylogenies, but I wonder if it can be used  on approximately-maximum-likelihood phylogenetic trees?

Many thanks for any information.

**Comment by jmcbroome-linkcell** [comment]
Sorry for the slow response. Yes, the method can apply to any numerical branch length; however, the idea of representing clusters with distinct shared genetic sequences doesn't quite apply in the same way. The code should just work out of the box on it.

**Comment by jmcbroome** [comment]
Sorry for the slow response. Yes, the method can apply to any numerical branch length; however, the idea of representing clusters with distinct shared genetic sequences doesn't quite apply in the same way. The code should just work out of the box on it.
